
export enum BusinessPermissionCodes
{
    ReadAppointment = "ReadAppointment",
	UpdateAppointment = "UpdateAppointment",
	InsertAppointment = "InsertAppointment",
	DeleteAppointment = "DeleteAppointment",
	ReadDisease = "ReadDisease",
	UpdateDisease = "UpdateDisease",
	InsertDisease = "InsertDisease",
	DeleteDisease = "DeleteDisease",
	ReadGender = "ReadGender",
	UpdateGender = "UpdateGender",
	InsertGender = "InsertGender",
	DeleteGender = "DeleteGender",
	ReadNotification = "ReadNotification",
	UpdateNotification = "UpdateNotification",
	InsertNotification = "InsertNotification",
	DeleteNotification = "DeleteNotification",
	ReadPatientDocument = "ReadPatientDocument",
	UpdatePatientDocument = "UpdatePatientDocument",
	InsertPatientDocument = "InsertPatientDocument",
	DeletePatientDocument = "DeletePatientDocument",
	ReadPatientDocumentDisease = "ReadPatientDocumentDisease",
	UpdatePatientDocumentDisease = "UpdatePatientDocumentDisease",
	InsertPatientDocumentDisease = "InsertPatientDocumentDisease",
	DeletePatientDocumentDisease = "DeletePatientDocumentDisease",
	ReadService = "ReadService",
	UpdateService = "UpdateService",
	InsertService = "InsertService",
	DeleteService = "DeleteService",
	ReadUserExtended = "ReadUserExtended",
	UpdateUserExtended = "UpdateUserExtended",
	InsertUserExtended = "InsertUserExtended",
	DeleteUserExtended = "DeleteUserExtended",
	ReadUserNotification = "ReadUserNotification",
	UpdateUserNotification = "UpdateUserNotification",
	InsertUserNotification = "InsertUserNotification",
	DeleteUserNotification = "DeleteUserNotification",
}


