import { Injectable } from '@angular/core';
import { TranslocoService } from '@jsverse/transloco';

@Injectable({
  providedIn: 'root',
})
export class TranslateLabelsGeneratedService {

    constructor(
        private translocoService: TranslocoService
    ) {
    }

    translate = (name: string): string => {
        switch(name) 
        {
            case 'doctorColor':
                return this.translocoService.translate('DoctorColor');
            case 'isCanceled':
                return this.translocoService.translate('IsCanceled');
            case 'reservedAt':
                return this.translocoService.translate('ReservedAt');
            case 'service':
                return this.translocoService.translate('Service');
            case 'expiredAt':
                return this.translocoService.translate('ExpiredAt');
            case 'doctor':
                return this.translocoService.translate('Doctor');
            case 'patient':
                return this.translocoService.translate('Patient');
            case 'id':
                return this.translocoService.translate('Id');
            case 'version':
                return this.translocoService.translate('Version');
            case 'createdAt':
                return this.translocoService.translate('CreatedAt');
            case 'modifiedAt':
                return this.translocoService.translate('ModifiedAt');
            case 'appointmentDTO':
                return this.translocoService.translate('AppointmentDTO');
            case 'user':
                return this.translocoService.translate('User');
            case 'email':
                return this.translocoService.translate('Email');
            case 'accessToken':
                return this.translocoService.translate('AccessToken');
            case 'refreshToken':
                return this.translocoService.translate('RefreshToken');
            case 'code':
                return this.translocoService.translate('Code');
            case 'name':
                return this.translocoService.translate('Name');
            case 'displayName':
                return this.translocoService.translate('DisplayName');
            case 'isLeaf':
                return this.translocoService.translate('IsLeaf');
            case 'diseaseDTO':
                return this.translocoService.translate('DiseaseDTO');
            case 'additionalColumnHeaders':
                return this.translocoService.translate('AdditionalColumnHeaders');
            case 'additionalDataStartColumn':
                return this.translocoService.translate('AdditionalDataStartColumn');
            case 'dataSheetName':
                return this.translocoService.translate('DataSheetName');
            case 'dataSheetName2':
                return this.translocoService.translate('DataSheetName2');
            case 'dataStartRow':
                return this.translocoService.translate('DataStartRow');
            case 'dataStartColumn':
                return this.translocoService.translate('DataStartColumn');
            case 'createNewDataRows':
                return this.translocoService.translate('CreateNewDataRows');
            case 'idToken':
                return this.translocoService.translate('IdToken');
            case 'browser':
                return this.translocoService.translate('Browser');
            case 'genderDTO':
                return this.translocoService.translate('GenderDTO');
            case 'userEmail':
                return this.translocoService.translate('UserEmail');
            case 'token':
                return this.translocoService.translate('Token');
            case 'selectedIds':
                return this.translocoService.translate('SelectedIds');
            case 'totalRecordsSelected':
                return this.translocoService.translate('TotalRecordsSelected');
            case 'expireAt':
                return this.translocoService.translate('ExpireAt');
            case 'isMarkedAsRead':
                return this.translocoService.translate('IsMarkedAsRead');
            case 'title':
                return this.translocoService.translate('Title');
            case 'description':
                return this.translocoService.translate('Description');
            case 'emailBody':
                return this.translocoService.translate('EmailBody');
            case 'notificationDTO':
                return this.translocoService.translate('NotificationDTO');
            case 'selectedRecipientsIds':
                return this.translocoService.translate('SelectedRecipientsIds');
            case 'unselectedRecipientsIds':
                return this.translocoService.translate('UnselectedRecipientsIds');
            case 'areAllRecipientsSelected':
                return this.translocoService.translate('AreAllRecipientsSelected');
            case 'recipientsTableFilter':
                return this.translocoService.translate('RecipientsTableFilter');
            case 'totalRecords':
                return this.translocoService.translate('TotalRecords');
            case 'query':
                return this.translocoService.translate('Query');
            case 'patientDocument':
                return this.translocoService.translate('PatientDocument');
            case 'disease':
                return this.translocoService.translate('Disease');
            case 'patientDocumentDiseaseDTO':
                return this.translocoService.translate('PatientDocumentDiseaseDTO');
            case 'isPatientUnhealthy':
                return this.translocoService.translate('IsPatientUnhealthy');
            case 'patientIllness':
                return this.translocoService.translate('PatientIllness');
            case 'isTreatedByDoctor':
                return this.translocoService.translate('IsTreatedByDoctor');
            case 'treatedIllness':
                return this.translocoService.translate('TreatedIllness');
            case 'hasBeenInHospital':
                return this.translocoService.translate('HasBeenInHospital');
            case 'medicationsTaking':
                return this.translocoService.translate('MedicationsTaking');
            case 'allergicToMedicationOrSomething':
                return this.translocoService.translate('AllergicToMedicationOrSomething');
            case 'treatedUnderLocalAnesthesia':
                return this.translocoService.translate('TreatedUnderLocalAnesthesia');
            case 'hasBleedingDisorder':
                return this.translocoService.translate('HasBleedingDisorder');
            case 'hasRadiationTherapy':
                return this.translocoService.translate('HasRadiationTherapy');
            case 'hasInfectiousDisease':
                return this.translocoService.translate('HasInfectiousDisease');
            case 'hadBloodTransfusion':
                return this.translocoService.translate('HadBloodTransfusion');
            case 'typeOfTransfusion':
                return this.translocoService.translate('TypeOfTransfusion');
            case 'dateOfTransfusion':
                return this.translocoService.translate('DateOfTransfusion');
            case 'hasAids':
                return this.translocoService.translate('HasAids');
            case 'isHivPositive':
                return this.translocoService.translate('IsHivPositive');
            case 'isPregnant':
                return this.translocoService.translate('IsPregnant');
            case 'deliveryDate':
                return this.translocoService.translate('DeliveryDate');
            case 'wantSixMonthTherapyMessage':
                return this.translocoService.translate('WantSixMonthTherapyMessage');
            case 'isAgreedToTreatment':
                return this.translocoService.translate('IsAgreedToTreatment');
            case 'patientDocumentDTO':
                return this.translocoService.translate('PatientDocumentDTO');
            case 'diseasesNamebookDTOList':
                return this.translocoService.translate('DiseasesNamebookDTOList');
            case 'selectedDiseasesIds':
                return this.translocoService.translate('SelectedDiseasesIds');
            case 'nameLatin':
                return this.translocoService.translate('NameLatin');
            case 'descriptionLatin':
                return this.translocoService.translate('DescriptionLatin');
            case 'permissionDTO':
                return this.translocoService.translate('PermissionDTO');
            case 'ipAddress':
                return this.translocoService.translate('IpAddress');
            case 'tokenString':
                return this.translocoService.translate('TokenString');
            case 'status':
                return this.translocoService.translate('Status');
            case 'message':
                return this.translocoService.translate('Message');
            case 'usersNamebookDTOList':
                return this.translocoService.translate('UsersNamebookDTOList');
            case 'roleDTO':
                return this.translocoService.translate('RoleDTO');
            case 'permissionsNamebookDTOList':
                return this.translocoService.translate('PermissionsNamebookDTOList');
            case 'role':
                return this.translocoService.translate('Role');
            case 'permission':
                return this.translocoService.translate('Permission');
            case 'rolePermissionDTO':
                return this.translocoService.translate('RolePermissionDTO');
            case 'selectedUsersIds':
                return this.translocoService.translate('SelectedUsersIds');
            case 'selectedPermissionsIds':
                return this.translocoService.translate('SelectedPermissionsIds');
            case 'duration':
                return this.translocoService.translate('Duration');
            case 'serviceDTO':
                return this.translocoService.translate('ServiceDTO');
            case 'value':
                return this.translocoService.translate('Value');
            case 'matchMode':
                return this.translocoService.translate('MatchMode');
            case 'operator':
                return this.translocoService.translate('Operator');
            case 'filters':
                return this.translocoService.translate('Filters');
            case 'first':
                return this.translocoService.translate('First');
            case 'rows':
                return this.translocoService.translate('Rows');
            case 'multiSortMeta':
                return this.translocoService.translate('MultiSortMeta');
            case 'additionalFilterIdInt':
                return this.translocoService.translate('AdditionalFilterIdInt');
            case 'additionalFilterIdLong':
                return this.translocoService.translate('AdditionalFilterIdLong');
            case 'field':
                return this.translocoService.translate('Field');
            case 'order':
                return this.translocoService.translate('Order');
            case 'data':
                return this.translocoService.translate('Data');
            case 'profilePictureBlobNameData':
                return this.translocoService.translate('ProfilePictureBlobNameData');
            case 'profilePictureBlobName':
                return this.translocoService.translate('ProfilePictureBlobName');
            case 'birthDate':
                return this.translocoService.translate('BirthDate');
            case 'hasLoggedInWithExternalProvider':
                return this.translocoService.translate('HasLoggedInWithExternalProvider');
            case 'isDisabled':
                return this.translocoService.translate('IsDisabled');
            case 'gender':
                return this.translocoService.translate('Gender');
            case 'userExtendedDTO':
                return this.translocoService.translate('UserExtendedDTO');
            case 'notification':
                return this.translocoService.translate('Notification');
            case 'userNotificationDTO':
                return this.translocoService.translate('UserNotificationDTO');
            case 'userRoleDTO':
                return this.translocoService.translate('UserRoleDTO');
            case 'verificationCode':
                return this.translocoService.translate('VerificationCode');
            default:
                return null;
        }
    }
}

